version: '3.9'

services:
  web:
    build: .
    command: bash -c "source /myprojects/alienv/bin/activate && python3 manage.py runserver 0.0.0.0:7000"
    restart: always
    image: djangoindocker
    container_name: murad
    volumes:
      - .:/mydockerproject
    ports:
      - "7000:7000"
    networks:
      - custom-net

networks:
  custom-net:
    external: true

