# Generated by Django 2.0.1 on 2018-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('slideshow_first_image', models.ImageField(blank=True, upload_to='img/slide', verbose_name='Slide show birinci sekil')),
                ('slideshow_second_image', models.ImageField(blank=True, upload_to='img/slide', verbose_name='Slide show ikinci sekil')),
                ('slideshow_first_h1', models.CharField(max_length=250, verbose_name='Slide show birinci basliq')),
                ('slideshow_first_p', models.CharField(max_length=250, verbose_name='Slide show birinci metin')),
                ('slideshow_second_h1', models.CharField(max_length=250, verbose_name='Slide show ikinci basliq')),
                ('slideshow_second_p', models.CharField(max_length=250, verbose_name='Slide show ikinci metin')),
            ],
        ),
        migrations.CreateModel(
            name='tablecell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tablecell_first_h4', models.CharField(max_length=250, verbose_name='Slide show birinci basliq')),
                ('tablecell_second_h4', models.CharField(max_length=250, verbose_name='Slide show ikinci basliq')),
                ('tablecell_first_h3', models.CharField(max_length=250, verbose_name='Slide show birinci kicik basliq')),
                ('tablecell_second_h3', models.CharField(max_length=250, verbose_name='Slide show ikinci kicik basliq')),
                ('tablecell_second_p', models.CharField(max_length=250, verbose_name='Slide show ikinci metin')),
                ('tablecell_first_p', models.CharField(max_length=250, verbose_name='Slide show birinci metin')),
                ('tablecell_first_img', models.ImageField(upload_to='img/banner', verbose_name='Slide show birinci sekil')),
                ('tablecell_second_img', models.ImageField(upload_to='img/banner', verbose_name='Slide show ikinci sekil')),
            ],
        ),
    ]
