# Generated by Django 2.0.1 on 2018-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_image_name', models.CharField(max_length=250, verbose_name='Sekilin adi')),
                ('product_image', models.ImageField(upload_to='img', verbose_name='Sekil')),
                ('product_image_sale', models.CharField(default=0, max_length=250, verbose_name='Satis qiymeti')),
                ('product_image_discount', models.CharField(max_length=250, null=True, verbose_name='Endirim')),
                ('product_image_new', models.CharField(max_length=250, null=True, verbose_name='Yeni?')),
                ('product_image_stock', models.CharField(max_length=250, null=True, verbose_name='Stokda?')),
                ('product_image_second_discount', models.CharField(max_length=250, null=True, verbose_name='Endirimden sonraki qiymeti')),
            ],
        ),
    ]
